//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kolisetka.Application.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kolisetka.Application.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu admin1@localhost.com.
        /// </summary>
        internal static string Test_InvalidUser_GetEmail {
            get {
                return ResourceManager.GetString("Test.InvalidUser.GetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu kotyToBumBum.
        /// </summary>
        internal static string Test_InvalidUser_GetPassword {
            get {
                return ResourceManager.GetString("Test.InvalidUser.GetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu bangBang.com.
        /// </summary>
        internal static string Test_InvalidUser_NewEmail {
            get {
                return ResourceManager.GetString("Test.InvalidUser.NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu StringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStrinStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringString.
        /// </summary>
        internal static string Test_InvalidUser_NewFirstName {
            get {
                return ResourceManager.GetString("Test.InvalidUser.NewFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu StringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStrinStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringString.
        /// </summary>
        internal static string Test_InvalidUser_NewLastName {
            get {
                return ResourceManager.GetString("Test.InvalidUser.NewLastName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu kotyToBumBum.
        /// </summary>
        internal static string Test_InvalidUser_NewPassword {
            get {
                return ResourceManager.GetString("Test.InvalidUser.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu StringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStrinStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringString.
        /// </summary>
        internal static string Test_InvalidUser_NewUserName {
            get {
                return ResourceManager.GetString("Test.InvalidUser.NewUserName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu StringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStriStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStriStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStriStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStriStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStriStringString [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Test_TooLongString_1001 {
            get {
                return ResourceManager.GetString("Test.TooLongString.1001", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu StringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStringStrin.
        /// </summary>
        internal static string Test_TooLongString_101 {
            get {
                return ResourceManager.GetString("Test.TooLongString.101", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu user@localhost.com.
        /// </summary>
        internal static string Test_ValidUser_GetEmail {
            get {
                return ResourceManager.GetString("Test.ValidUser.GetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu System.
        /// </summary>
        internal static string Test_ValidUser_GetFirstName {
            get {
                return ResourceManager.GetString("Test.ValidUser.GetFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 0be5b79b-d566-4fb1-b9f7-9aa1115d889b.
        /// </summary>
        internal static string Test_ValidUser_GetId {
            get {
                return ResourceManager.GetString("Test.ValidUser.GetId", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User.
        /// </summary>
        internal static string Test_ValidUser_GetLastName {
            get {
                return ResourceManager.GetString("Test.ValidUser.GetLastName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu user@localhost.com.
        /// </summary>
        internal static string Test_ValidUser_GetUserName {
            get {
                return ResourceManager.GetString("Test.ValidUser.GetUserName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu jan@brzechwa.com.
        /// </summary>
        internal static string Test_ValidUser_NewEmail {
            get {
                return ResourceManager.GetString("Test.ValidUser.NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jan.
        /// </summary>
        internal static string Test_ValidUser_NewFirstName {
            get {
                return ResourceManager.GetString("Test.ValidUser.NewFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brzechwa.
        /// </summary>
        internal static string Test_ValidUser_NewLastName {
            get {
                return ResourceManager.GetString("Test.ValidUser.NewLastName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu kotyToBumBum!2.
        /// </summary>
        internal static string Test_ValidUser_NewPassword {
            get {
                return ResourceManager.GetString("Test.ValidUser.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PiriPiri.
        /// </summary>
        internal static string Test_ValidUser_NewUserName {
            get {
                return ResourceManager.GetString("Test.ValidUser.NewUserName", resourceCulture);
            }
        }
    }
}
